DROP SEQUENCE seq_utilisateur;
DROP SEQUENCE seq_agenda;
DROP SEQUENCE seq_activite;
DROP SEQUENCE seq_archive_activite;
DROP SEQUENCE seq_archive_agenda;


DROP TABLE ARCHIVE_AGENDA;
DROP TABLE ARCHIVE_ACTIVITE;
DROP TABLE ACTIVITE_SUPPRIME;
DROP TABLE AGENDA_SUPPRIME;
DROP TABLE UTILISATEUR_AGENDA;
DROP TABLE UTILISATEUR_ACTIVITE;
DROP TABLE AGENDA_ACTIVITE;
DROP TABLE ACTIVITE;
DROP TABLE AGENDA;
DROP TABLE UTILISATEUR;
